// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnI0z0m9r56wRdFsIVQlMXnussDdasLpY',
    appId: '1:810873962575:web:71a8ae5bc4c003740d2a3a',
    messagingSenderId: '810873962575',
    projectId: 'irctc6712',
    authDomain: 'irctc6712.firebaseapp.com',
    storageBucket: 'irctc6712.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP_Y3Q3FaxTHsRQoIK0xzYVhI32lgQWpU',
    appId: '1:810873962575:android:f5992f5b5e2872cc0d2a3a',
    messagingSenderId: '810873962575',
    projectId: 'irctc6712',
    storageBucket: 'irctc6712.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2s4uisp73NjnmoFNFWHY8MjVtzYvzyNs',
    appId: '1:810873962575:ios:74f3430790ae5c240d2a3a',
    messagingSenderId: '810873962575',
    projectId: 'irctc6712',
    storageBucket: 'irctc6712.appspot.com',
    iosBundleId: 'com.example.irctc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2s4uisp73NjnmoFNFWHY8MjVtzYvzyNs',
    appId: '1:810873962575:ios:74f3430790ae5c240d2a3a',
    messagingSenderId: '810873962575',
    projectId: 'irctc6712',
    storageBucket: 'irctc6712.appspot.com',
    iosBundleId: 'com.example.irctc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnI0z0m9r56wRdFsIVQlMXnussDdasLpY',
    appId: '1:810873962575:web:ace846fc19bb2b680d2a3a',
    messagingSenderId: '810873962575',
    projectId: 'irctc6712',
    authDomain: 'irctc6712.firebaseapp.com',
    storageBucket: 'irctc6712.appspot.com',
  );
}
